# Site settings
title: 'typedef Sukeesh'
email: vsukeeshbabu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soft copy of my thoughts and imaginations..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sukeesh.me" # the base hostname & protocol for your site
twitter_username: sukeeshbabu
github_username:  vsukeeshbabu
facebook_username: '100001115883149'

# Build settings
markdown: kramdown
