kmarkdown: rdiscount
rouge: true
permalink: /archive/:year/:title.html
rdiscount:
  extensions: [smart]


future: true  
name: Sukeesh
url: http://sukeesh.github.io
description: Software Developer and Metallurgy undergrad at IIT Roorkee
twitter: sukeeshbabu
github: sukeesh
gravatar_url: http://www.gravatar.com/avatar/644617b452dc50fb071ed4b36ccfaa41

google_analytics_tracking_id: UA-73546079-1
