# Site settings
title:          Sukeesh
description:    "Personal blog"
baseurl:        "/blog"
url:            "https://sukeesh.com"

# Google Analytics
google_analytics: UA-64535283-1

# Author
author:
  name:         Sukeesh
  url:          https://sukeesh.com
  email:        vsukeeshbabu@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
